apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ml-autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: ml-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 25
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 90
        periodSeconds: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80